services:

  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - DB_URL=postgresql://postgres:postgres@db:5432/tekovia
    depends_on:
      - db

  frontend:
    build:
      context: ..
      dockerfile: frontend/Dockerfile 
    ports:
      - "3000:3000"
    depends_on:
      - api

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tekovia
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


