version: "3.8"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tekovia
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_URL=postgresql+psycopg2://postgres:admin@db:5432/tekovia

volumes:
  postgres_data:
