version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: tekovia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./api
    environment:
      DB_URL: postgresql+psycopg2://postgres:admin@db:5432/tekovia
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    image: ghcr.io/reflex-dev/reflex-standalone:0.7.14
    volumes:
      - ../monolith/.web:/app/.web          # ruta al export local
    ports:
      - "3000:3000"
    depends_on:
      - api


volumes:
  dbdata:
